name: message-hub-stack

services:
  api:
    image: ghcr.io/hasanjaved-developer/message-hub/api:v1.0.1
    container_name: centralized_logging_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      
    ports:
      - "5000:8080"   # Map host:container for HTTP
      - "5001:8081"   # Map host:container for HTTPS (if your app supports it)   
    depends_on:
      db:
        condition: service_healthy
      jaeger:
        condition: service_started
      dragonfly:
        condition: service_started        
    volumes:
      - ./CentralizedLoggingApi/logs:/app/logs

  userapi:
    image: ghcr.io/hasanjaved-developer/message-hub/userapi:v1.0.1

    container_name: user_management_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      
    ports:
      - "6000:8080"   # Host 6000 -> container 8080 (HTTP)
      # - "6001:8081" # Optional HTTPS mapping if your app listens on 8081
    depends_on:
      db:
        condition: service_healthy
      jaeger:
        condition: service_started
      dragonfly:
        condition: service_started
    volumes:
      - ./UserManagementApi/logs:/app/logs

  web:

    image: ghcr.io/hasanjaved-developer/message-hub/web:v1.0.1
    container_name: api_integration_web
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      # Point the web app to APIs by service name (DNS provided by Compose)
      - Services__CentralizedLogging__BaseUrl=http://api:8080
      - Services__UserManagement__BaseUrl=http://userapi:8080
    ports:
      - "7000:8080"  # browse http://localhost:7000
    depends_on:
      api:
        condition: service_started
      userapi:
        condition: service_started
      jaeger:
        condition: service_started
      dragonfly:
        condition: service_started

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: centralized_logging_db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Bisp@123

    ports:
      - "1433:1433"  

    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost,1433 -U sa -P 'Bisp@123' -C -Q \"SELECT 1\""]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    volumes:
      - sql_data:/var/opt/mssql

  # Jaeger (all-in-one: UI + collector + agent + storage)
  jaeger:
    image: jaegertracing/all-in-one:1.57
    container_name: jaeger
    ports:
      - "16686:16686"   # Jaeger UI
      - "4317:4317"     # OTLP gRPC (traces)
      - "4318:4318"     # OTLP HTTP (traces)
    environment:
      - LOG_LEVEL=info

  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly:v1.24.0
    container_name: dragonfly
    command: ["--requirepass=Bisp@123"]
    ports:
      - "6379:6379"
    volumes:
      - dflydata:/data
    restart: unless-stopped

volumes:
  sql_data:
  dflydata:
